name: hellodekal
description: "UniCafe - Food Ordering App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.5
  
  # Core utilities
  collection: ^1.19.1
  intl: ^0.20.2
  
  # Firebase - Backend services
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.11
  firebase_database: ^11.1.7  # For real-time order tracking
  
  # UI Components
  flutter_credit_card: ^4.1.0
  
  # NEW ADDITIONS for Figma design features:
  
  # Phone Authentication
  country_code_picker: ^3.0.0      # Country code selection
  pinput: ^5.0.0                   # OTP input fields
  
  # Maps & Location
  google_maps_flutter: ^2.9.0     # For delivery tracking map
  geolocator: ^13.0.1             # Location services
  geocoding: ^3.0.0               # Address conversion
  
  # QR Code
  qr_flutter: ^4.1.0              # Generate QR codes for payment
  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner.git  # Scan QR codes
  
  # Images & UI
  cached_network_image: ^3.4.1    # Optimized image loading
  shimmer: ^3.0.0                 # Loading animations
  smooth_page_indicator: ^1.2.0   # Page indicators for onboarding
  
  # Animations & Effects
  lottie: ^3.1.3                  # Beautiful animations
  flutter_staggered_animations: ^1.1.1  # List animations
  
  # Utilities
  url_launcher: ^6.3.1            # Launch external URLs
  share_plus: ^10.1.1             # Share functionality
  image_picker: ^1.1.2            # Profile image picker
  
  # HTTP & Networking (if needed for additional APIs)
  http: ^1.2.2

dev_dependencies:
  flutter_test:
   sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons: 
  android: true
  ios: true
  image_path: "lib/images/logo/unicafelogo_png.png" # Replace with your icon path

flutter:
  uses-material-design: true

  # Assets - Organized by feature
  assets:
    - lib/images/v1/
    - lib/images/v2/
    - lib/images/v3/
    - lib/images/v4/
    - lib/images/v5/
    - lib/images/v6/
    - lib/images/logo/
    - lib/images/bg/

  # Custom fonts (optional - can add Google Fonts later)
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700
