// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Secret',
    appId: '1:202442075141:web:38119b3370b08fe693806c',
    messagingSenderId: '202442075141',
    projectId: 'unicafefoodorder',
    authDomain: 'unicafefoodorder.firebaseapp.com',
    storageBucket: 'unicafefoodorder.firebasestorage.app',
    measurementId: 'G-QTW59F1LVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Secret',
    appId: '1:202442075141:android:759c33a239b8dbc193806c',
    messagingSenderId: '202442075141',
    projectId: 'unicafefoodorder',
    storageBucket: 'unicafefoodorder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Secret',
    appId: '1:202442075141:ios:0fc9aaa7b031a3d893806c',
    messagingSenderId: '202442075141',
    projectId: 'unicafefoodorder',
    storageBucket: 'unicafeAIzaSyApeIJUHFSGZR5Zs6FQCAcflfjcTGcMVOwfoodorder.firebasestorage.app',
    iosBundleId: 'com.example.hellodekal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'Secret',
    appId: '1:202442075141:ios:0fc9aaa7b031a3d893806c',
    messagingSenderId: '202442075141',
    projectId: 'unicafefoodorder',
    storageBucket: 'unicafefoodorder.firebasestorage.app',
    iosBundleId: 'com.example.hellodekal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'Secret',
    appId: '1:202442075141:web:37cfcd5af427158d93806c',
    messagingSenderId: '202442075141',
    projectId: 'unicafefoodorder',
    authDomain: 'unicafefoodorder.firebaseapp.com',
    storageBucket: 'unicafefoodorder.firebasestorage.app',
    measurementId: 'G-74QBBFSVB5',
  );
}
